package gr.peptidetracker.app

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import gr.peptidetracker.app.data.*
import gr.peptidetracker.app.domain.PeptideCalculator
import java.text.DateFormat
import java.util.Date

class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);enableEdgeToEdge();setContent{PeptideApp(LocalStore(this))}}}
private val Blue=Color(0xFF0D47A1);private val Mint=Color(0xFF00A896)
data class Nav(val label:String,val icon:androidx.compose.ui.graphics.vector.ImageVector)

@Composable fun PeptideApp(store:LocalStore){var dark by remember{mutableStateOf(store.darkMode())};val colors=if(dark)darkColorScheme(primary=Color(0xFF9CCAFF),secondary=Color(0xFF62DCCB))else lightColorScheme(primary=Blue,secondary=Mint);MaterialTheme(colors){AppShell(store,dark){dark=it;store.setDarkMode(it)}}}
@Composable private fun AppShell(store:LocalStore,dark:Boolean,setDark:(Boolean)->Unit){var tab by remember{mutableIntStateOf(0)};var detail by remember{mutableStateOf<PeptideInfo?>(null)};val nav=listOf(Nav("Αρχική",Icons.Outlined.Home),Nav("Πεπτίδια",Icons.Outlined.Science),Nav("Υπολογιστής",Icons.Outlined.Calculate),Nav("Tracker",Icons.Outlined.Timeline),Nav("Περισσότερα",Icons.Outlined.MoreHoriz));Scaffold(bottomBar={NavigationBar{nav.forEachIndexed{i,n->NavigationBarItem(selected=tab==i,onClick={tab=i;detail=null},icon={Icon(n.icon,null)},label={Text(n.label,maxLines=1)})}}}){pad->Surface(Modifier.fillMaxSize().padding(pad)){detail?.let{PeptideDetail(it,{detail=null},store)}?:when(tab){0->Dashboard(store){tab=it};1->Library(store){detail=it};2->Calculator();3->Tracker(store);else->More(store,dark,setDark)}}}}
@Composable private fun Header(title:String,sub:String?=null,back:(()->Unit)?=null){Row(verticalAlignment=Alignment.CenterVertically){back?.let{IconButton(it){Icon(Icons.Default.ArrowBack,"Πίσω")}};Column{Text(title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);sub?.let{Text(it,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}
@Composable private fun Metric(title:String,value:String,m:Modifier=Modifier){Card(m){Column(Modifier.padding(14.dp)){Text(value,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text(title,style=MaterialTheme.typography.bodySmall)}}}
@Composable private fun Dashboard(store:LocalStore,go:(Int)->Unit){val last=store.entries().firstOrNull();LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Header("Peptide Tracker GR","Offline research toolkit")};item{Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.primaryContainer)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Icon(Icons.Outlined.Calculate,null,Modifier.size(34.dp));Text("Υπολογιστής Πεπτιδίων",fontWeight=FontWeight.Bold);Text("Συγκέντρωση, όγκος και μονάδες U-100.");Button({go(2)}){Text("Υπολόγισε τώρα")}}}};item{Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("Τελευταίο peptide",last?.peptide?:"—",Modifier.weight(1f));Metric("Καταγραφές",store.entries().size.toString(),Modifier.weight(1f))}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){AssistChip({go(1)},{Text("Βιβλιοθήκη")},leadingIcon={Icon(Icons.Outlined.Science,null)});AssistChip({go(3)},{Text("Νέα καταγραφή")},leadingIcon={Icon(Icons.Default.Add,null)})}}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun Library(store:LocalStore,open:(PeptideInfo)->Unit){var q by remember{mutableStateOf("")};var onlyFav by remember{mutableStateOf(false)};var favs by remember{mutableStateOf(store.favorites())};Column(Modifier.fillMaxSize().padding(top=16.dp)){Column(Modifier.padding(horizontal=18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Header("Βιβλιοθήκη Πεπτιδίων","Πάτησε ένα πεπτίδιο για πλήρη ανάλυση");OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),label={Text("Αναζήτηση")},leadingIcon={Icon(Icons.Default.Search,null)});FilterChip(onlyFav,{onlyFav=!onlyFav},{Text("Μόνο αγαπημένα")},leadingIcon={Icon(Icons.Outlined.FavoriteBorder,null)})};LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){items(peptideCatalog.filter{it.name.contains(q,true)||it.alias.contains(q,true)}.filter{!onlyFav||it.id in favs},key={it.id}){p->Card(onClick={open(p)},modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Surface(color=MaterialTheme.colorScheme.secondaryContainer,shape=MaterialTheme.shapes.medium){Icon(Icons.Outlined.Biotech,null,Modifier.padding(11.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(p.name,fontWeight=FontWeight.Bold);Text(p.category,color=MaterialTheme.colorScheme.primary,style=MaterialTheme.typography.labelMedium);Text(p.status,maxLines=1,style=MaterialTheme.typography.bodySmall)};IconButton({store.toggleFavorite(p.id);favs=store.favorites()}){Icon(if(p.id in favs)Icons.Default.Favorite else Icons.Outlined.FavoriteBorder,"Αγαπημένο")};Icon(Icons.Default.ChevronRight,null)}}}}}}
@Composable private fun PeptideDetail(p:PeptideInfo,back:()->Unit,store:LocalStore){val ctx=LocalContext.current;var fav by remember{mutableStateOf(p.id in store.favorites())};LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.weight(1f)){Header(p.name,p.alias,back)};IconButton({store.toggleFavorite(p.id);fav=!fav}){Icon(if(fav)Icons.Default.Favorite else Icons.Outlined.FavoriteBorder,null)}}};item{Surface(color=MaterialTheme.colorScheme.tertiaryContainer,shape=MaterialTheme.shapes.large){Column(Modifier.padding(14.dp)){Text("Κατάσταση",fontWeight=FontWeight.Bold);Text(p.status)}}};item{Info("Επιστημονική επισκόπηση",p.overview,Icons.Outlined.Science)};item{Info("Σε τι έρευνα χρησιμοποιείται",p.research,Icons.Outlined.ManageSearch)};item{Info("Μηχανισμός",p.mechanism,Icons.Outlined.Hub)};item{Info("Περιορισμοί",p.warning,Icons.Outlined.Warning)};item{Text("Κλινικές μελέτες & πηγές",fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleMedium)};items(p.studies){s->OutlinedCard(onClick={ctx.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(s.url)))},modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Outlined.Article,null);Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(s.title,fontWeight=FontWeight.SemiBold);Text(s.source,style=MaterialTheme.typography.bodySmall)};Icon(Icons.Outlined.OpenInNew,null)}}};item{Text("Ενημερωτικό περιεχόμενο — όχι ιατρική συμβουλή ή οδηγία χρήσης.",style=MaterialTheme.typography.bodySmall)}}
@Composable private fun Info(title:String,text:String,icon:androidx.compose.ui.graphics.vector.ImageVector){Card{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Icon(icon,null,tint=MaterialTheme.colorScheme.primary);Text(title,fontWeight=FontWeight.Bold);Text(text)}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun Calculator(){var reverse by remember{mutableStateOf(false)};var cap by remember{mutableIntStateOf(30)};var vial by remember{mutableStateOf("5")};var water by remember{mutableStateOf("1")};var target by remember{mutableStateOf("0.1")};var units by remember{mutableStateOf("5")};var out by remember{mutableStateOf<List<String>>(emptyList())};var error by remember{mutableStateOf("")};LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("Υπολογιστής Πεπτιδίων","Native έκδοση του calculator του PeptidiaStore")};item{SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){listOf("Ποσότητα → U","U → Ποσότητα").forEachIndexed{i,t->SegmentedButton(reverse==(i==1),{reverse=i==1},SegmentedButtonDefaults.itemShape(i,2)){Text(t)}}}};item{Step(1,"Όγκος Σύριγγας","Κλίμακα U-100",Icons.Outlined.Vaccines){Pills(listOf("30","50","100"),cap.toString()){cap=it.toInt()}}};item{Step(2,"Φιαλίδιο Πεπτιδίου","Συνολική ποσότητα (mg)",Icons.Outlined.Biotech){Preset(vial,{vial=it},listOf("5","10","20","30"),"mg")}};item{Step(3,"Βακτηριοστατικό Νερό","Όγκος διαλύτη (ml)",Icons.Outlined.WaterDrop){Preset(water,{water=it},listOf("1","2","3","5"),"ml");if((water.toDoubleOrNull()?:0.0)>3)Text("⚠ Μεγαλύτερος όγκος από τυπικό φιαλίδιο",color=MaterialTheme.colorScheme.error)}};item{Step(4,if(reverse)"Μονάδες Σύριγγας" else "Επιθυμητή Ποσότητα",if(reverse)"Ένδειξη U-100" else "Τιμή που εισάγει ο χρήστης (mg)",Icons.Outlined.MyLocation){if(reverse)Num("Μονάδες",units){units=it}else Preset(target,{target=it},listOf("0.1","0.25","0.5","1"),"mg")}};item{Button(modifier=Modifier.fillMaxWidth().height(52.dp),onClick={try{val v=vial.toDouble();val w=water.toDouble();out=if(!reverse){val r=PeptideCalculator.dose(v,w,target.toDouble(),true,100);listOf("${PeptideCalculator.format(r.syringeUnits,2)} U","${PeptideCalculator.format(r.volumeMl,4)} ml","${PeptideCalculator.format(r.concentrationMgPerMl,3)} mg/ml")}else{val r=PeptideCalculator.reverse(v,w,units.toDouble(),100);listOf("${PeptideCalculator.format(r.amountMg,4)} mg","${PeptideCalculator.format(r.amountMcg,2)} mcg","${PeptideCalculator.format(r.volumeMl,4)} ml")};error=""}catch(_:Exception){error="Συμπλήρωσε έγκυρες θετικές τιμές."}}){Icon(Icons.Default.Calculate,null);Spacer(Modifier.width(8.dp));Text("Υπολογισμός")}};if(error.isNotEmpty())item{Text(error,color=MaterialTheme.colorScheme.error)};if(out.isNotEmpty())item{Result(out,cap)};item{Text("Μαθηματική μετατροπή μόνο. Δεν προτείνεται ποσότητα, πρωτόκολλο ή θεραπεία.",style=MaterialTheme.typography.bodySmall)}}}
@Composable private fun Step(n:Int,title:String,sub:String,icon:androidx.compose.ui.graphics.vector.ImageVector,body:@Composable ColumnScope.()->Unit){Card{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(color=MaterialTheme.colorScheme.primaryContainer,shape=MaterialTheme.shapes.medium){Icon(icon,null,Modifier.padding(10.dp))};Spacer(Modifier.width(10.dp));Column{Text("$n. $title",fontWeight=FontWeight.Bold);Text(sub,style=MaterialTheme.typography.bodySmall)}};body()}}}
@Composable private fun Pills(v:List<String>,selected:String,on:(String)->Unit){Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){v.forEach{FilterChip(it==selected,{on(it)},{Text(it)})}}}
@Composable private fun Preset(value:String,on:(String)->Unit,p:List<String>,unit:String){Pills(p,value,on);Num("Προσαρμοσμένη τιμή ($unit)",value,on)}
@Composable private fun Num(label:String,value:String,on:(String)->Unit)=OutlinedTextField(value,{on(it.replace(',','.'))},Modifier.fillMaxWidth(),label={Text(label)},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Decimal),singleLine=true)
@Composable private fun Result(out:List<String>,cap:Int){val u=out[0].substringBefore(" ").toDoubleOrNull()?:0.0;Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.primaryContainer)){Column(Modifier.padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(9.dp)){Text(out[0],style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.Bold);Text(out.drop(1).joinToString("  •  "));LinearProgressIndicator(progress={(u/cap).coerceIn(0.0,1.0).toFloat()},modifier=Modifier.fillMaxWidth());Text("Χωρητικότητα: $cap U");if(u>cap)Text("Η ένδειξη υπερβαίνει τη χωρητικότητα.",color=MaterialTheme.colorScheme.error)}}}

@Composable private fun Tracker(store:LocalStore){var peptide by remember{mutableStateOf("")};var amount by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};var rows by remember{mutableStateOf(store.entries())};LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){item{Header("Tracker","Οι καταγραφές μένουν στη συσκευή")};item{OutlinedTextField(peptide,{peptide=it},Modifier.fillMaxWidth(),label={Text("Πεπτίδιο")})};item{OutlinedTextField(amount,{amount=it},Modifier.fillMaxWidth(),label={Text("Ποσότητα και μονάδα")})};item{OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Σημείωση")})};item{Button({store.add(peptide,amount,note);rows=store.entries();peptide="";amount="";note=""},enabled=peptide.isNotBlank()&&amount.isNotBlank()){Icon(Icons.Default.Save,null);Text(" Αποθήκευση")}};if(rows.isEmpty())item{Text("Δεν υπάρχουν καταγραφές.")}else items(rows,key={it.id}){r->Card{Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(r.peptide,fontWeight=FontWeight.Bold);Text(r.amount);if(r.note.isNotBlank())Text(r.note);Text(DateFormat.getDateTimeInstance().format(Date(r.createdAt)),style=MaterialTheme.typography.bodySmall)};IconButton({store.deleteEntry(r.id);rows=store.entries()}){Icon(Icons.Outlined.Delete,"Διαγραφή")}}}}}}
@Composable private fun More(store:LocalStore,dark:Boolean,setDark:(Boolean)->Unit){var page by remember{mutableIntStateOf(0)};when(page){1->Inventory(store){page=0};2->Progress(store){page=0};else->LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Header("Περισσότερα")};item{Button({page=1},Modifier.fillMaxWidth()){Icon(Icons.Outlined.Inventory2,null);Text(" Απόθεμα φιαλιδίων")}};item{Button({page=2},Modifier.fillMaxWidth()){Icon(Icons.Outlined.MonitorWeight,null);Text(" Μετρήσεις προόδου")}};item{Card{Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Outlined.DarkMode,null);Text("  Σκούρο θέμα",Modifier.weight(1f));Switch(dark,setDark)}}};item{Info("Απόρρητο","Tracker, απόθεμα και μετρήσεις αποθηκεύονται τοπικά και δεν αποστέλλονται σε διαφημιστικά συστήματα.",Icons.Outlined.Security)};item{Text("Έκδοση 1.1.0")}}}}
@Composable private fun Inventory(store:LocalStore,back:()->Unit){var name by remember{mutableStateOf("")};var vial by remember{mutableStateOf("10")};var qty by remember{mutableStateOf("1")};var batch by remember{mutableStateOf("")};var rows by remember{mutableStateOf(store.inventory())};LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){item{Header("Απόθεμα",back=back)};item{OutlinedTextField(name,{name=it},Modifier.fillMaxWidth(),label={Text("Πεπτίδιο")})};item{Num("Φιαλίδιο (mg)",vial){vial=it}};item{Num("Ποσότητα",qty){qty=it}};item{OutlinedTextField(batch,{batch=it},Modifier.fillMaxWidth(),label={Text("Batch / lot")})};item{Button({store.addInventory(name,vial.toDouble(),qty.toInt(),batch);rows=store.inventory();name=""},enabled=name.isNotBlank()&&vial.toDoubleOrNull()!=null&&qty.toIntOrNull()!=null){Text("Προσθήκη")}};items(rows,key={it.id}){r->Card{Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(r.peptide,fontWeight=FontWeight.Bold);Text("${r.quantity} × ${r.vialMg} mg • ${r.batch.ifBlank{"Χωρίς batch"}}")};IconButton({store.deleteInventory(r.id);rows=store.inventory()}){Icon(Icons.Outlined.Delete,null)}}}}}}
@Composable private fun Progress(store:LocalStore,back:()->Unit){var weight by remember{mutableStateOf("")};var waist by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};var rows by remember{mutableStateOf(store.progress())};LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){item{Header("Μετρήσεις προόδου",back=back)};item{Num("Βάρος (kg)",weight){weight=it}};item{Num("Μέση (cm, προαιρετικό)",waist){waist=it}};item{OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Σημείωση")})};item{Button({store.addProgress(weight.toDouble(),waist.toDoubleOrNull(),note);rows=store.progress();weight="";waist="";note=""},enabled=weight.toDoubleOrNull()!=null){Text("Αποθήκευση")}};if(rows.size>1)item{Metric("Συνολική μεταβολή","${PeptideCalculator.format(rows.first().weight-rows.last().weight,1)} kg",Modifier.fillMaxWidth())};items(rows,key={it.id}){r->Card{Column(Modifier.padding(14.dp)){Text("${r.weight} kg",fontWeight=FontWeight.Bold);r.waist?.let{Text("Μέση: $it cm")};if(r.note.isNotBlank())Text(r.note);Text(DateFormat.getDateInstance().format(Date(r.createdAt)),style=MaterialTheme.typography.bodySmall)}}}}}
